# -*- coding: utf-8 -*-
# =============================================================================
# Copyright (C) Les solutions géostack, Inc
#
# This file was produced as part of a research project conducted for
# The World Bank Group and is licensed under the terms of the MIT license.
#
# For inquiries, contact: info@geostack.ca
# Repository: https://github.com/geo-stack/hydrodepthml
# =============================================================================

"""
Train and evaluate the machine learning model for water table
depth prediction.

This script performs the following tasks:

1. Loads the training dataset containing topographic, geomorphometric, and
   climatic features along with water table depth observations.
2. Splits the dataset into training (80%) and testing (20%) sets. It uses a
   grouped split based on watershed IDs (HYBAS_ID) by default to ensure spatial
   independence and test extrapolation capabilities.
3. Trains an XGBoost regression model with optimized hyperparameters.
4. Applies sample weighting to penalize errors on underrepresented deep water
   table values, correcting the model's prediction bias (ceiling effect).
5. Evaluates the model's performance by generating learning curves (RMSE and
   Mean Error), feature importance plots, and predicted vs. observed scatter
   plots.
6. Retrains the final model on the complete dataset and exports it as a pickle
   file for subsequent spatial prediction (cartography).

Requirements
------------
- Training dataset CSV file (generated by '08_create_training_dataset.py').

Outputs
-------
- 'model/wtd_predict_model.pkl':
      The trained model, including feature names and training date.
- Various Matplotlib figures evaluating the training process and model
  accuracy.

Note that all paths are relative to the repository's 'data/' directory
(e.g., 'C:/Users/User/Documents/hydrodepthml/data/').
"""

# ---- Standard imports
from datetime import datetime
import pickle

# ---- Third party imports
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import GroupShuffleSplit
import xgboost as xgb

# ---- Local imports
from hdml import __datadir__ as datadir
from hdml.modeling import plot_pred_vs_obs
from hdml.ml_helpers import (plot_feature_importance, plot_learning_curves)

model_path = datadir / 'model' / 'wtd_predict_model.pkl'

wtd_path = datadir / 'model' / 'wtd_obs_training_dataset_sig1_st500.csv'

if not wtd_path.exists():
    raise FileNotFoundError(
        "Make sure to run '08_create_training_dataset.py' before running "
        "this script to generate your training dataset."
        )

df = pd.read_csv(wtd_path)

MODELTYPE = 'xgboost'  # 'xgboost' or 'support_vector'

TEST_COUNTRY = [
    'Burkina',  # 0
    'Guinee',   # 1
    'Benin',    # 2
    'Mali',     # 3
    'Chad',     # 4
    'Niger',    # 5
    'Togo',     # 6
    None,       # 7
    ][3]

# =============================================================================
# FEATURE DESCRIPTIONS
# =============================================================================
#
# Dependent Variable
# ------------------
# NS:
#     Observation of the depth of the water table in meters
#     below the ground surface.
#
# Topographic and Spatial Features
# --------------------------------
# dist_stream:
#     Euclidean distance to the nearest stream pixel in meters.
#     dist_stream = ((point_x - stream_x)**2 + (point_y - stream_y)**2)**0.5
# alt_stream:
#     Elevation difference (m) from the point to the nearest stream.
#     alt_stream = point_z - stream_z
# ratio_stream:
#     Overall slope ratio towards the nearest stream.
#     ratio_stream = alt_stream / max(dist_stream, pixel_size)
# dist_divide:
#     Euclidean distance (m) to the nearest watershed boundary.
#     Boundaries are derived from D8 subbasins using streams.
#     dist_divide = ((point_x - divide_x)**2 + (point_y - divide_y)**2)**0.5
# alt_divide:
#     Elevation difference (m) from the nearest watershed boundary
#     to the observation point.
#     alt_divide = divide_z - point_z
# ratio_stream_divide:
#     Relative position of point between stream and the watershed boundary.
#     ratio = dist_stream / (dist_divide + dist_stream)
# wetness_index:
#     Topographic Wetness Index (TWI) representing soil moisture
#     accumulation patterns.
#
# Geomorphometric Statistics
# --------------------------
# long_grad_*:
#     Descriptive statistics of the slope (first derivative of elevation)
#     over a 41-pixel window (1230 m -> 615 m halfwidth).
# short_grad_*:
#     Descriptive statistics of the slope (first derivative of elevation)
#     over a 7-pixel window (210 m -> 105 m halfwidth).
# stream_grad_*:
#     Descriptive statistics of the slope (first derivative of elevation)
#     calculated along a Bresenham line between the point and the nearest
#     stream.
# long_hessian_*:
#     Descriptive statistics of the terrain curvature (second derivative
#     of elevation) over a 41-pixel window (1230 m -> 615 m halfwidth).
# stream_hessian_*:
#     Descriptive statistics of the terrain curvature (second derivative
#     of elevation) calculated along a Bresenham line between the point
#     and the nearest stream.
#
# Climatic and Environmental Features
# -----------------------------------
# ndvi:
#     Mean daily Normalized Difference Vegetation Index (NDVI) averaged
#     over a period of time before each specific observation. The length
#     of the averaged time window depends on the size of the watershed
#     containing the observation point.
# precipitation:
#     Mean daily precipitation (mm) averaged over a period of time before
#     each specific observation. The length of the averaged time window
#     depends on the size of the watershed containing the observation point.
# pre_mm_syr:
#     Average annual precipitation (mm/year) for the sub-basin.
# tmp_dc_syr:
#     Average annual air temperature (°C) for the sub-basin.
# pet_mm_syr:
#     Average annual potential evapotranspiration (mm/year) for the sub-basin.
# =============================================================================

# List of features to use for training the model.
# Comment out features you do not want to use.

FEATURES = [
    # ---- TOPOGRAPHIC AND SPATIAL FEATURES
    'dist_stream',
    'alt_stream',
    'ratio_stream',
    'dist_divide',
    'alt_divide',
    'ratio_stream_divide',
    'wetness_index',
    # ---- GEOMORPHOMETRIC STATISTICS
    # 'long_hessian_max',
    # 'long_hessian_mean',
    # 'long_hessian_var',
    # 'long_hessian_skew',
    # 'long_hessian_kurt',
    # 'long_grad_mean',
    # 'long_grad_var',
    # 'short_grad_max',
    # 'short_grad_var',
    # 'short_grad_mean',
    # 'stream_grad_max',
    # 'stream_grad_var',
    # 'stream_grad_mean',
    # 'stream_hessian_max',
    # ---- CLIMATIC AND ENVIRONMENTAL FEATURES
    'ndvi',
    'precipitation',
    'pre_mm_syr',
    'tmp_dc_syr',
    'pet_mm_syr',
    ]

# %%


def eval_mean_error(y_true, y_pred):
    me = np.mean(y_true - y_pred)
    return float(me)


# Split training and test set.

plt.close('all')

if TEST_COUNTRY is not None:
    df_resample = df.loc[df.country == TEST_COUNTRY].copy()
else:
    df_resample = df.copy()

df_resample = df_resample.reset_index(drop=True)

# Define features (X), target (y), and groups (HYBAS_ID) for the split.
X = df_resample[FEATURES]
y = df_resample['NS']


from hdml.ml_helpers import plot_ns_distribution
plot_ns_distribution(y.values)

RANDOM_SPLIT = True

if TEST_COUNTRY == 'Mali' and RANDOM_SPLIT is False:
    train_idx = df_resample[df_resample.LON < -6].index.astype(int)
    test_idx = df_resample[df_resample.LON > -6].index.astype(int)
else:
    # Grouped split by watershed (20% of watersheds for the test set).
    groups = df_resample['HYBAS_ID']
    gss = GroupShuffleSplit(
        n_splits=1,
        test_size=0.2,
        random_state=12
        )
    train_idx, test_idx = next(gss.split(X, y, groups))

df_train = df_resample.iloc[train_idx]
df_test = df_resample.iloc[test_idx]

# Visualize the spatial distribution of the train and test sets.
fig2, ax2 = plt.subplots()
ax2.plot(df_train.LON, df_train.LAT, '.', color='orange', label='Train (80%)')
ax2.plot(df_test.LON, df_test.LAT, '.', color='blue', label='Test (20%)')
ax2.set_title("Spatial distribution (Split by HYBAS_ID)")
ax2.legend()
fig2.tight_layout()

# Extract NumPy arrays for model training.
X_train = X.iloc[train_idx].values
X_test = X.iloc[test_idx].values
y_train = y.iloc[train_idx].values
y_test = y.iloc[test_idx].values

params = {
    'subsample': 0.8,
    'colsample_bytree': 0.75,

    'reg_lambda': 2.0,
    'reg_alpha': 0.5,

    'max_depth': 5,

    'n_estimators': 300,
    'learning_rate': 0.1,
    'gamma': 0.1,

    'eval_metric': eval_mean_error,
    }


weights = np.ones(len(y_train))
weights[y_train > 10] = 2

Cl = xgb_model = xgb.XGBRegressor(**params)
Cl.fit(X_train, y_train,
       sample_weight=weights,
       eval_set=[(X_train, y_train), (X_test, y_test)],
       verbose=False,
       )

fig_lc = plot_learning_curves(Cl)

# Check feature importances and validate model fit.
fig3 = plot_feature_importance(Cl.feature_importances_, FEATURES)

y_eval = Cl.predict(X_test)

if TEST_COUNTRY is None:
    classes = np.full(len(y_test), 'All data (test)')
else:
    classes = np.full(len(y_test), f'{TEST_COUNTRY} (test)')

axis = {'xmin': 0, 'xmax': 30, 'ymin': 0, 'ymax': 30}
fig4 = plot_pred_vs_obs(
    y_test, y_eval, classes, axis=axis,
    suptitle='True vs Predicted values',
    plot_stats=True,
    )
fig4.tight_layout()

y_eval = Cl.predict(X_train)

if TEST_COUNTRY is None:
    classes = np.full(len(y_eval), 'All data (test)')
else:
    classes = np.full(len(y_eval), f'{TEST_COUNTRY} (test)')

fig5 = plot_pred_vs_obs(
    y_train, y_eval, classes, axis=axis,
    suptitle='True vs Predicted values',
    plot_stats=True
    )


# %%

# Train model on the entire dataset and save model to disk.

X_train = df[FEATURES]
y_train = df['NS']

weights = np.ones(len(y_train))
weights[y_train > 10] = 2

Cl = xgb_model = xgb.XGBRegressor(**params)

Cl.fit(X_train, y_train, sample_weight=weights)

# Save the model.
model_data = {
    'model': Cl,
    'feature_names': FEATURES,
    'training_date': datetime.now().strftime('%Y-%m-%d')
    }
with open(model_path, 'wb') as f:
    pickle.dump(model_data, f)
